config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'recipes#index'
  get 'recipe_categories' => 'recipes#recipe_by_category'
  get 'items_by_category' => 'recipes#items_by_category'
  resources :recipes do
    resources :reviews, except: [:show, :index]
  end
  resources :comments
  devise_for :users
  resources :categories
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :comment_entry, :recipe_id, presence: true, length: {maximum: 500, too_long: 'Comment cannot exceed 500 characters.'}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]


  def edit;
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html {redirect_to recipe_path(id: @comment.recipe_id), notice: 'Comment posted.'}
      else
        format.html {redirect_to recipe_path(id: @comment.recipe_id), notice: 'Comment failed to post!'}
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to recipe_path(id: @comment.recipe_id), notice: 'Comment was updated!'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to recipe_path(id: @comment.recipe_id), notice: 'Comment deleted!'}
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_entry, :recipe_id, :user_id, :user_name, :name)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% @recipe.comments.each do |comment| %>
<div class="" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document" style="font-size: 36px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="word-wrap: break-word;"><%= simple_format("@#{comment.user.user_name}") + ' | ' + comment.created_at.strftime('%D at %I:%M %p') + ' |' %></h5>
      </div>
      <div class="modal-body">
        <p style="word-wrap: break-word;"><%= simple_format(comment.comment_entry.html_safe) %></p>
      </div>
      <div class="modal-footer">
      <% if current_user.id == comment.user_id || current_user.admin? %>
        <%= link_to 'Edit Comment', edit_comment_path(comment), class: 'btn btn-warning' %>
        <%= link_to 'Delete Comment', comment_path(comment), method: :delete, data: {confirm: 'Are you sure you want to delete this comment?'}, class: 'btn btn-danger' %>
      <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/comments/_comments_form.html.erb
<div class="container">
  <div class="container">
    <%= form_with(model: @comment, local: true) do |f| %>

      <br>
      <div class="form-group">
        <%= f.text_area :comment_entry, class: 'form-control', rows: 8, width: 5, placeholder: 'Enter comment here...', style: 'font-size: 24px; border: solid #333333' %>
      </div>

      <%= f.hidden_field :recipe_id, value: @recipe.id %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="actions">
        <%= f.submit 'Submit', class: 'btn btn-block btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_edit_comments.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <br>
  <div class="form-group">
    <%= f.text_area :comment_entry, class: 'form-control', rows: 8, width: 5, placeholder: 'Enter comment here...', style: 'font-size: 24px;' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-block btn-primary'%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render 'edit_comments' %>
<%= link_to 'Back', :back %>