config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'recipes#index'
  get 'recipe_categories' => 'recipes#recipe_by_category'
  get 'items_by_category' => 'recipes#items_by_category'
  resources :recipes do
    resources :reviews, except: [:show, :index]
  end
  resources :comments
  devise_for :users
  resources :categories
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :ingredient_list, :name, :instruction_list, presence: true
  validates :instruction_list, :ingredient_list, presence: true
  validates :description, presence: true, uniqueness: true

  has_many :comments, dependent: :destroy
  has_many :reviews

  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[edit show create update destroy new]


  def index
    @recipes = if params[:term]
                 Recipe.where('name ILIKE ?', "%#{params[:term]}").page(params[:page]).per(3)
               else
                 Recipe.all.page(params[:page]).per(3)
               end
  end

  def show
    @comment = Comment.new
    @reviews = Review.where(recipe_id: @recipe.user_id).order('created_at DESC')

    if @reviews.blank?
      @avg_review = 0.00
    else
      @avg_review = @reviews.average(:rating).round(2, :default)
    end
  end

  def edit
    @categories = Category.all
  end

  def new
    @recipe = Recipe.new
    @categories = Category.all
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html {redirect_to recipe_path(@recipe), notice: 'Recipe was created.'}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html {redirect_to recipe_path(@recipe), notice: 'Recipe updated!'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html {redirect_to '/', notice: 'Recipe was deleted.'}
    end
  end

  def recipe_by_category
    @categories = Category.all
  end

  def items_by_category
    @recipes = Recipe.where(category_id: params[:cat_id]).page(params[:page]).per(2)
    @category = Category.find(params[:cat_id])
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:ingredient_list, :instruction_list, :user_id, :name, :description, :image, :user_name, :category_id, :remote_image_url, :term)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: @recipe, local: true) do |form| %>
    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@recipe.errors.count, 'error') %> prevented this from being made.</h2>
        <ul>
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Enter recipe name...' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 10, columns: 100, class: 'form-control', placeholder: 'Enter description...' %>
    </div>

    <div class="form-group">
      <%= form.label :ingredient_list %>
      <%= form.text_area :ingredient_list, rows: 10, columns: 100, class: 'form-control', placeholder: 'Enter recipe ingredients...' %>
    </div>

    <div class="form-group">
      <%= form.label :instruction_list %>
      <%= form.text_area :instruction_list, rows: 10, columns: 100, class: 'form-control', placeholder: 'Enter recipe instructions...' %>
    </div>

    <div class="form-group">
      <p>Upload an Image</p>
      <%= form.file_field :image, class: 'btn btn-block btn-success', style: "color: #000; padding: 0; margin: 0;" %>
    </div>
    <small> <em>OR</em> </small>
    <div class="form-group">
      <small>Enter URL to an image</small>
      <%= form.text_field :remote_image_url, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :category_id %>
      <%= form.select(:category_id, @categories.collect{|c| [c.name, c.id]}, {include_blank: 'Select Category'}, required: true, class: 'form-control') %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
<% else %>
  <h1>Please sign in to create new recipe!</h1>
  <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary btn-block' %>
  <%= link_to 'Register Account', edit_user_session_path %>
<% end %>

app/views/recipes/edit.html.erb
<% if current_user.id == @recipe.user_id %>
<%= render 'form' %>
<% end %>

app/views/recipes/index.html.erb
  <div class="recipe-container">
    <% @recipes.each do |recipe| %>
      <div class="card">
        <%= link_to (image_tag (recipe.image.url), {class: 'card-img-top img-responsive'}), recipe_path(recipe) %>
        <div class="card-body">
          <h4 class="card-title><span style=" text-decoration: underline;><%= simple_format(recipe.name.html_safe) %></h4>
          <h4><%= "@#{recipe.user.user_name}" %></h4>
          <%= @rating %>
          <small style="word-wrap: break-word;"><%= simple_format(recipe.created_at.strftime('%m/%d/%Y at %I:%M%p')) %></small>
          <br>
          <% if user_signed_in? %>
            <%= link_to 'See More', recipe_path(recipe), class: 'btn btn-primary btn-block' %><br>
            <% if current_user.id == recipe.user_id || current_user.admin? %>
              <%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-warning' %>
              <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>


<%= paginate @recipes %>

app/views/recipes/items_by_category.html.erb
All <%= @category.name %>
<%= paginate @recipes %>
<div class="row" style="margin-right: auto; margin-left: auto; ">
  <% @recipes.each do |recipe| %>
    <div class="card" style="width: 20rem; margin: 1rem;">
      <%= image_tag recipe.image, class: 'card-img-top' %>
      <div class="card-body">
        <h4 class="card-title><span style=" text-decoration: underline;>Recipe
          Name:</span> <%= simple_format(recipe.name.html_safe) %></h4>
        <p class="card-text"><span style="text-decoration: underline;">Recipe Description:</span>
          <%= simple_format(recipe.description.html_safe.truncate(50)) %>
        </p>
        <h4>Created by: <%= "@#{recipe.user.user_name}" %></h4>
        <p>Category: <%= recipe.category.name %></p>
        <small style="word-wrap: break-word;"><%= simple_format(recipe.created_at.strftime('%m/%d/%Y at %I:%M%p')) %></small>
        <br>
        <% if user_signed_in? %>
          <%= link_to 'Comments', recipe_path(recipe), class: 'btn btn-primary btn-block' %><br>
          <% if current_user.id == recipe.user_id || current_user.admin? %>
            <%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-warning' %>
            <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<% if user_signed_in? %>
<%= render 'form' %>
<br>
<% else %>
  <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary btn-block'%>
  <%= link_to 'Register Account', edit_user_registration_path, class: 'btn btn-secondary btn-block' %>
<%end%>

app/views/recipes/show.html.erb
    <div class="card single-card">
      <%= image_tag @recipe.image, class: 'card-img-top' %>
      <% unless @avg_review.blank? %>
        <div class="star-rating" style="display: table; margin-right: auto; margin-left: auto;" data-score="<%= @avg_review %>"></div>
        <em style="display: table; margin-right: auto; margin-left: auto;">
          <% if @reviews.length < 2 %>
            <%= @reviews.length %> review
          <% elsif @reviews.to_s.length %>
            <%= @reviews.length %> reviews
          <% end %>
        </em>
      <% end %>
      <div class="card-body">
        <h2 class="card-title" style="text-decoration: underline;">Recipe
          Name: <%= simple_format(@recipe.name.html_safe) %></h2>
        <p class="card-text">
          <span style="text-decoration: underline;">Recipe Description:</span><br> <%= simple_format(@recipe.description.html_safe) %>
        </p>
        <p class="card-text">
          <span style="text-decoration: underline;">Recipe Ingredients:</span><br> <%= simple_format(@recipe.ingredient_list.html_safe) %>
        </p>
        <p class=" card-text">
          <span style="text-decoration: underline;">Recipe Instructions:</span><br> <%= simple_format(@recipe.instruction_list.html_safe) %>
        </p>
        <p>Category: <%= @recipe.category.name %></p>
        <small><%= @recipe.created_at.strftime('%B %d, %Y at %I:%M%p') %></small>
        <br>
        <% if !current_user.id == @recipe.user_id %>
          <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-warning' %>
          <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: 'btn btn-danger' %>
        <% end %>
        <% if !@reviews.pluck(:user_id).include?(current_user.id) %>
          <%= link_to 'Rate Recipe', new_recipe_review_path(@recipe), class: 'btn btn-primary rate-button' %>
        <% else %>
          <%= "<h2>Thanks for voting :)</h2>".html_safe %>
        <% end %>

    <%= link_to 'Home', '/', class: 'btn btn-secondary btn-block' %>
    <%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-secondary btn-block' %>
    <%= render 'comments/comments_form' %>
    <%= render 'comments/comments' %>
  </div>
</div>
<script>
    $('.star-rating').raty({
        path: '/images',
        readOnly: true,
        score: function () {
            return $(this)('data-score');
        }
    });
</script>