config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'recipes#index'
  get 'recipe_categories' => 'recipes#recipe_by_category'
  get 'items_by_category' => 'recipes#items_by_category'
  resources :recipes do
    resources :reviews, except: [:show, :index]
  end
  resources :comments
  devise_for :users
  resources :categories
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  belongs_to :user

  validates :name, uniqueness: true, presence: true
  validates :user_id, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :show, :update, :destroy]

  def admin_only
    if current_user.admin?
    else
      redirect_to '/'
    end
  end

  def index
    if current_user.admin?
      @categories = Category.all
    end
  end

  def new
      @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html {redirect_to categories_path, notice: 'Category created!'}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {redirect_to category_path(@category), notice: 'category was updated'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html {redirect_to categories_path, notice: 'Category deleted'}
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <% pluralize(@category.errors.count, 'error') %> prohibited category from being saved.
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </h2>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', autofocus: true %>
  </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="form-group">
      <%= form.submit 'Create Category', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<head>
  <style>
    body {
      height: 100vh;
    }
  </style>
</head>

<h1> All Categories </h1>
  <table class="table table-responsive table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
    </tr>
    </thead>
    <% @categories.order(name: :asc).each do |category| %>
  <tbody>
    <tr>
      <td><%= category.name %></td>
      <td><%= "@#{category.user.user_name}" %></td>
      <% if current_user.id == category.user_id || current_user.role == "admin" %>
      <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning' %></td>
      <td><%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure you want to delete this category?'}, class: 'btn btn-danger' %></td>
      <% end %>
    </tr>
    </tbody>
    <% end %>
  </table>
<%= link_to 'Create New Category', new_category_path, class: 'btn btn-primary' %>

app/views/categories/new.html.erb
<%= render 'form' %>