config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'recipes#index'
  get 'recipe_categories' => 'recipes#recipe_by_category'
  get 'items_by_category' => 'recipes#items_by_category'
  resources :recipes do
    resources :reviews, except: [:show, :index]
  end
  resources :comments
  devise_for :users
  resources :categories
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<% if current_user.nil? && params[:action] == "index" && params[:controller] == "recipes" %>
  <style>
    body {
      height: 100vh;
    }
    @media (max-width: 750px) {
      body {
        height: auto;
      }
    }
}
  </style>
<% end %>
<nav class="navbar navbar-expand-xl navbar-light" style="background: transparent; display: flex; justify-content: center; align-items: center;">
  <%= link_to (image_tag 'https://image.ibb.co/dn6MX6/oie_transparent.png'), '/', class: 'navbar-brand mx-auto', width: 200 %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarLg">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="collapsingNavbarLg">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'New Recipe', new_recipe_path, class: 'nav-link' %>
        </li>

        <li class="dropdown nav-link">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
            <li><%= link_to category.name, items_by_category_path(cat_id: category.id) %></li>
            <% end %>
          </ul>
        </li>        
        <li class="nav-item">
          <%= link_to 'Add Category', categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure you want to sign out?'}, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <%= form_with(url: recipes_path, method: :get, local: true) do |form| %>
      <%= form.text_field(:term, {class: 'form-control', arialabel:'search', placeholder: 'search by recipe name'})%>
      <%= form.submit 'Search', class: 'btn btn-dark bg-dark' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharerecipes</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Boogaloo" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
</head>

<body>
<p class="welcome-user-by-name"><%= "Welcome @"+current_user.name if current_user %></p>
<%= render 'layouts/nav' %>
<!--<div class="container" style='background: url("https://images.pexels.com/photos/33486/soup-vegetables-pot-cooking.jpg?w=1260&h=750&auto=compress&cs=tinysrgb") no-repeat center center fixed; background-size: cover;'>-->
<div class="container">
  <%= yield %>
</div>
<nav class="footer">
  <ul>
    <li class="footer-title"><strong>Contact Info</strong></li>
    <li>Brian Ruff</li>
    <li>brff19@gmail.com</li>
    <li>867-5309</li>
  </ul>
  <ul>
    <li class="footer-title"><strong>Languages</strong></li>
    <li>Ruby on Rails</li>
    <li>HTML</li>
    <li>CSS</li>
  </ul>
  <ul>
    <li class="footer-title"><strong>More Languages & Doc Material</strong></li>
    <li>JavaScript</li>
    <li>ERB</li>
    <li>MDN</li>
  </ul>
</nav>
</body>
</html>